--USE MINI_PROJECTS--
-----RENAMING THE DABASE---------------------------
ALTER DATABASE MINI_PROJECTS
MODIFY NAME= LIBRARY_MANAGEMENT_SYSTEM


-------------(STUDENT TABLE)------------------------


CREATE TABLE STUDENTS(
 STUDENT_ID INT IDENTITY(1,1) NOT NULL,
 STUDENT_NAME VARCHAR(20) NOT NULL,
 GRADE INT NOT NULL,
 CONTACT_NO VARCHAR(20) NOT NULL
 CONSTRAINT PK_STD PRIMARY KEY (STUDENT_ID),
 CONSTRAINT GRADE_CHECK CHECK ( GRADE BETWEEN 1 AND 12)
)

-------------(BOOK TABLE)------------------------

CREATE TABLE BOOKS(
	BOOK_ID INT IDENTITY(1,1) NOT NULL,
	BOOK_TITLE VARCHAR(30) NOT NULL,
	CATEGORY VARCHAR(20),
	TOTAL_COPIES INT NOT NULL,
	COPIES INT NOT NULL,
	CONSTRAINT PK_BOOK PRIMARY KEY (BOOK_ID)
)

EXEC sp_rename 'BOOKS.COPIES', 'AVAILABLE_COPIES', 'COLUMN'

ALTER TABLE BOOKS
ADD 
	CONSTRAINT CK_Total_Copies CHECK (TOTAL_COPIES > 0),
	CONSTRAINT CK_Available_Copies CHECK (AVAILABLE_COPIES >= 0 AND AVAILABLE_COPIES <= TOTAL_COPIES)

-------------( AUTHOR TABLE )------------------------

CREATE TABLE AUTHOR(
	AUTHOR_ID INT IDENTITY(1,1) NOT NULL,
	AUTHOR_NAME VARCHAR(20) NOT NULL,
	CONSTRAINT PK_AUTHOR PRIMARY KEY ( AUTHOR_ID )
	)

-------------(BOOK AUTHORS TABLE)------------------------

CREATE TABLE BOOK_AUTHORS(
	BOOK_ID INT NOT NULL,
	AUTHOR_ID INT NOT NULL,
	CONSTRAINT PK_BOOK_AUTHORS PRIMARY KEY (BOOK_ID, AUTHOR_ID),
	CONSTRAINT FK_BOOKS FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID),
	CONSTRAINT FK_AUTHOR FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(AUTHOR_ID)
)


-------------(STAFF TABLE)------------------------

CREATE TABLE STAFF (
	STAFF_ID INT IDENTITY(1,1) NOT NULL,
	STAFF_NAME VARCHAR(20) NOT NULL,
	ROLE VARCHAR(30),
	CONTACT_NO VARCHAR(20) NOT NULL,
	CONSTRAINT PK_STAFF PRIMARY KEY (STAFF_ID)
)


-------------(BORROW RECORDS TABLE)------------------------

CREATE TABLE BORROW_RECORDS(
	LOG_ID INT IDENTITY(1,1) NOT NULL,
	STUDENT_ID INT NOT NULL,
	BOOK_ID INT NOT NULL,
	STAFF_ID INT NOT NULL,
	ISSUE_DATE DATE NOT NULL,
	DUE_DATE DATE NOT NULL,
	RETURN_DATE DATE NOT NULL,
	CONSTRAINT BR_RECORDS_PK PRIMARY KEY (LOG_ID),
	CONSTRAINT FK_STD_ID FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID),
	CONSTRAINT FK_BOOK_ID FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID)
	)
ALTER TABLE BORROW_RECORDS
ADD CONSTRAINT FK_STAFF FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID)

ALTER TABLE BORROW_RECORDS
ADD CONSTRAINT CK_RETURN_DATE CHECK (RETURN_DATE IS NULL OR RETURN_DATE >= ISSUE_DATE)

ALTER TABLE BORROW_RECORDS
ALTER COLUMN RETURN_DATE DATE NULL
-----------------------------------------------------------------------------------------


